meta_product_name: "Chazaq"
meta_title: "Chazaq - Take Heart In"
meta_description: "Faith Community for prayer support and testimonial celebrations"
meta_image: "" # should exist in `app/assets/images/`
twitter_account: "@chazaq"   # required for Twitter Cards
