meta_product_name: "CHAZAQ"
meta_title: "CHAZAQ: Take Heart in"
meta_description: "Faith based community for sharing prayer request and testinomonial celebrations."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@chazaq"   # required for Twitter Cards
